
INSERT INTO LOCATIONS (LOCATION_NAME, LOCATION_X, LOCATION_Y) VALUES ('bathroom', 98, 38);
INSERT INTO LOCATIONS (LOCATION_NAME, LOCATION_X, LOCATION_Y) VALUES ('bedroom', 56, 368);
INSERT INTO LOCATIONS (LOCATION_NAME, LOCATION_X, LOCATION_Y) VALUES ('kitchen', 1028, 370);
INSERT INTO LOCATIONS (LOCATION_NAME, LOCATION_X, LOCATION_Y) VALUES ('living room', 1036, 54);
INSERT INTO LOCATIONS (LOCATION_NAME, LOCATION_X, LOCATION_Y) VALUES ('closet', 38, 132);

INSERT INTO ADJECTIVES (adjective_id, adjective_name) VALUES (1, 'red');
INSERT INTO ADJECTIVES (adjective_id, adjective_name) VALUES (2, 'yellow');
INSERT INTO ADJECTIVES (adjective_id, adjective_name) VALUES (3, 'heavy');
INSERT INTO ADJECTIVES (adjective_id, adjective_name) VALUES (4, 'light');

INSERT INTO ATTRIBUTES (ATTRIBUTE_ID, ATTRIBUTE_NAME) VALUES (1, 'color');
INSERT INTO ATTRIBUTES (ATTRIBUTE_ID, ATTRIBUTE_NAME) VALUES (2, 'weight');
INSERT INTO ATTRIBUTES (ATTRIBUTE_ID, ATTRIBUTE_NAME) VALUES (3, 'texture');
INSERT INTO ATTRIBUTES (ATTRIBUTE_ID, ATTRIBUTE_NAME) VALUES (4, 'volume');
INSERT INTO ATTRIBUTES (ATTRIBUTE_ID, ATTRIBUTE_NAME) VALUES (5, 'x_position');
INSERT INTO ATTRIBUTES (ATTRIBUTE_ID, ATTRIBUTE_NAME) VALUES (6, 'y_position');

INSERT INTO ADJECTIVE_TYPE (attribute_id, adjective_id) VALUES (1, 1);
INSERT INTO ADJECTIVE_TYPE (attribute_id, adjective_id) VALUES (1, 2);
INSERT INTO ADJECTIVE_TYPE (attribute_id, adjective_id) VALUES (2, 3);
INSERT INTO ADJECTIVE_TYPE (attribute_id, adjective_id) VALUES (2, 4);
INSERT INTO ADJECTIVE_TYPE (attribute_id, adjective_id) VALUES (1, 5);

INSERT INTO QUANTIFIERS (q_id, q_name) VALUES (1, 'all');
INSERT INTO QUANTIFIERS (q_id, q_name) VALUES (2, 'some');

INSERT INTO COMPARATORS (COMPARATOR_ID, LESS_THAN, GREATER_THAN, EQUAL) VALUES (1, 'lighter', 'heavier', 'as heavy as');